---
title: "Ayush Oberoi's Blog"
date: 2020-12-13
---
title: My Personal Blog
author: Ayush Oberoi
email: ayushoberoi55@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Ayush Oberoi , studying in final year of computer engineering. I'm Interested in Azure cloud, coding and automating stuffs using python.
  I aspire to become a senior site reliability engineer at Microsoft.
  

# social links
twitter_username: https://twitter.com/ZieL_05 # DO NOT include the @ character, or else the build will fail!
github_username:  https://github.com/ayush-oberoi # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

